import type { Metadata } from "next";
import { Barlow_Semi_Condensed } from "next/font/google";
import Head from "next/head";
import "../styles/global.css";
import { ContextProvider } from "./context";

const barlow_Semi_Condensed = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "advanced rock, papper, scissors game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={barlow_Semi_Condensed.className}>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
